$path = "e:\Projects_code\Flutter\application\lib\screens\appearing_screens\course_details_page.dart"
$lines = [System.IO.File]::ReadAllLines($path)
$newLines = New-Object System.Collections.Generic.List[string]

$inOldBuild = $false
$inOldTitleRow = $false
$inOldCourseImage = $false

foreach ($line in $lines) {
    # Replace build method body
    if ($line -like "*Widget build(BuildContext context) {*") {
        $newLines.Add("  @override")
        $newLines.Add("  Widget build(BuildContext context) {")
        $newLines.Add("    final theme = Theme.of(context);")
        $newLines.Add("    final isDark = theme.brightness == Brightness.dark;")
        $newLines.Add("    ")
        $newLines.Add("    return Scaffold(")
        $newLines.Add("      backgroundColor: theme.scaffoldBackgroundColor,")
        $newLines.Add("      body: Container(")
        $newLines.Add("        height: MediaQuery.of(context).size.height * 0.95,")
        $newLines.Add("        decoration: BoxDecoration(")
        $newLines.Add("          color: theme.scaffoldBackgroundColor,")
        $newLines.Add("          borderRadius: const BorderRadius.vertical(top: Radius.circular(32)),")
        $newLines.Add("        ),")
        $newLines.Add("        child: Stack(")
        $newLines.Add("          children: [")
        $newLines.Add("            Column(")
        $newLines.Add("              children: [")
        $newLines.Add("                _buildNotchHandle(),")
        $newLines.Add("                Expanded(")
        $newLines.Add("                  child: SingleChildScrollView(")
        $newLines.Add("                    padding: const EdgeInsets.fromLTRB(16, 8, 16, 120),")
        $newLines.Add("                    child: Column(")
        $newLines.Add("                      crossAxisAlignment: CrossAxisAlignment.start,")
        $newLines.Add("                      children: [")
        $newLines.Add("                        _buildVideoHeader(),")
        $newLines.Add("                        const SizedBox(height: 24),")
        $newLines.Add("                        _buildCourseInfo(theme),")
        $newLines.Add("                        const SizedBox(height: 12),")
        $newLines.Add("                        _buildStatsRow(isDark),")
        $newLines.Add("                        const SizedBox(height: 32),")
        $newLines.Add("                        Align(")
        $newLines.Add("                          alignment: Alignment.centerRight,")
        $newLines.Add("                          child: Text(")
        $newLines.Add("                            AppLocalizations.of(context)!.courseContent,")
        $newLines.Add("                            style: GoogleFonts.cairo(")
        $newLines.Add("                              color: theme.textTheme.titleMedium?.color,")
        $newLines.Add("                              fontSize: 16,")
        $newLines.Add("                              fontWeight: FontWeight.w800,")
        $newLines.Add("                            ),")
        $newLines.Add("                          ),")
        $newLines.Add("                        ),")
        $newLines.Add("                        const SizedBox(height: 16),")
        $newLines.Add("                        _buildTabs(),")
        $newLines.Add("                        const SizedBox(height: 16),")
        $newLines.Add("                        _buildTabContent(),")
        $newLines.Add("                      ],")
        $newLines.Add("                    ),")
        $newLines.Add("                  ),")
        $newLines.Add("                ),")
        $newLines.Add("              ],")
        $newLines.Add("            ),")
        $newLines.Add("            Positioned(")
        $newLines.Add("              bottom: 0,")
        $newLines.Add("              left: 0,")
        $newLines.Add("              right: 0,")
        $newLines.Add("              child: _buildBottomBar(isDark),")
        $newLines.Add("            ),")
        $newLines.Add("          ],")
        $newLines.Add("        ),")
        $newLines.Add("      ),")
        $newLines.Add("    );")
        $newLines.Add("  }")
        $inOldBuild = $true
        continue
    }

    if ($inOldBuild) {
        if ($line -like "*_buildTabContent(),*") {
            # This is near the end of build
        }
        if ($line -eq "  }") {
            $inOldBuild = $false
        }
        continue
    }

    # Replace TitleRow with CourseInfo
    if ($line -like "*Widget _buildTitleRow(ThemeData theme) {*") {
        $newLines.Add("  Widget _buildCourseInfo(ThemeData theme) {")
        $newLines.Add("    return Column(")
        $newLines.Add("      crossAxisAlignment: CrossAxisAlignment.end,")
        $newLines.Add("      children: [")
        $newLines.Add("        Row(")
        $newLines.Add("          mainAxisAlignment: MainAxisAlignment.spaceBetween,")
        $newLines.Add("          children: [")
        $newLines.Add("            Container(")
        $newLines.Add("              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),")
        $newLines.Add("              decoration: BoxDecoration(")
        $newLines.Add("                color: const Color(0xFFFFF3F1),")
        $newLines.Add("                borderRadius: BorderRadius.circular(10),")
        $newLines.Add("              ),")
        $newLines.Add("              child: Row(")
        $newLines.Add("                children: [")
        $newLines.Add("                  Text(")
        $newLines.Add('                    "XP 500+",')
        $newLines.Add("                    style: GoogleFonts.cairo(")
        $newLines.Add("                      color: const Color(0xFFFF6B4A),")
        $newLines.Add("                      fontSize: 12,")
        $newLines.Add("                      fontWeight: FontWeight.w800,")
        $newLines.Add("                    ),")
        $newLines.Add("                  ),")
        $newLines.Add("                  const SizedBox(width: 4),")
        $newLines.Add("                  Image.network(")
        $newLines.Add('                    "https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Activities/Wrapped%20Gift.png",')
        $newLines.Add("                    width: 16,")
        $newLines.Add("                    height: 16,")
        $newLines.Add("                  ),")
        $newLines.Add("                ],")
        $newLines.Add("              ),")
        $newLines.Add("            ),")
        $newLines.Add("            Expanded(")
        $newLines.Add("              child: Text(")
        $newLines.Add("                widget.title,")
        $newLines.Add("                textAlign: TextAlign.right,")
        $newLines.Add("                style: GoogleFonts.cairo(")
        $newLines.Add("                  fontSize: 22,")
        $newLines.Add("                  fontWeight: FontWeight.w900,")
        $newLines.Add("                  color: theme.textTheme.titleLarge?.color,")
        $newLines.Add("                ),")
        $newLines.Add("              ),")
        $newLines.Add("            ),")
        $newLines.Add("          ],")
        $newLines.Add("        ),")
        $newLines.Add("        const SizedBox(height: 8),")
        $newLines.Add("        Row(")
        $newLines.Add("          mainAxisAlignment: MainAxisAlignment.end,")
        $newLines.Add("          children: [")
        $newLines.Add("            Text(")
        $newLines.Add('              " | الصف الثالث الثانوي",')
        $newLines.Add("              style: GoogleFonts.cairo(")
        $newLines.Add("                fontSize: 14,")
        $newLines.Add("                fontWeight: FontWeight.w700,")
        $newLines.Add("                color: Colors.grey,")
        $newLines.Add("              ),")
        $newLines.Add("            ),")
        $newLines.Add("            Text(")
        $newLines.Add('              widget.teacherName ?? "أ. محمد عبد المعبود",')
        $newLines.Add("              style: GoogleFonts.cairo(")
        $newLines.Add("                fontSize: 14,")
        $newLines.Add("                fontWeight: FontWeight.w800,")
        $newLines.Add("                color: AppColors.sky,")
        $newLines.Add("              ),")
        $newLines.Add("            ),")
        $newLines.Add("            const SizedBox(width: 8),")
        $newLines.Add("            const Icon(PhosphorIconsFill.users, color: Colors.grey, size: 18),")
        $newLines.Add("          ],")
        $newLines.Add("        ),")
        $newLines.Add("      ],")
        $newLines.Add("    );")
        $newLines.Add("  }")
        $inOldTitleRow = $true
        continue
    }

    if ($inOldTitleRow) {
        if ($line -eq "  }") {
            $inOldTitleRow = $false
        }
        continue
    }

    # Replace CourseImage with VideoHeader
    if ($line -like "*Widget _buildCourseImage() {*") {
        $newLines.Add("  Widget _buildVideoHeader() {")
        $newLines.Add("    return Container(")
        $newLines.Add("      height: 220,")
        $newLines.Add("      width: double.infinity,")
        $newLines.Add("      decoration: BoxDecoration(")
        $newLines.Add("        borderRadius: BorderRadius.circular(24),")
        $newLines.Add("        image: DecorationImage(")
        $newLines.Add("          image: NetworkImage(widget.image),")
        $newLines.Add("          fit: BoxFit.cover,")
        $newLines.Add("        ),")
        $newLines.Add("      ),")
        $newLines.Add("      child: Stack(")
        $newLines.Add("        children: [")
        $newLines.Add("          Container(")
        $newLines.Add("            decoration: BoxDecoration(")
        $newLines.Add("              borderRadius: BorderRadius.circular(24),")
        $newLines.Add("              color: Colors.black.withOpacity(0.2),")
        $newLines.Add("            ),")
        $newLines.Add("          ),")
        $newLines.Add("          Positioned(")
        $newLines.Add("            top: 16,")
        $newLines.Add("            right: 16,")
        $newLines.Add("            child: Container(")
        $newLines.Add("              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),")
        $newLines.Add("              decoration: BoxDecoration(")
        $newLines.Add("                color: Colors.black.withOpacity(0.5),")
        $newLines.Add("                borderRadius: BorderRadius.circular(8),")
        $newLines.Add("              ),")
        $newLines.Add("              child: Text(")
        $newLines.Add('                "اعلان الكورس",')
        $newLines.Add("                style: GoogleFonts.cairo(")
        $newLines.Add("                  color: Colors.white,")
        $newLines.Add("                  fontSize: 12,")
        $newLines.Add("                  fontWeight: FontWeight.w700,")
        $newLines.Add("                ),")
        $newLines.Add("              ),")
        $newLines.Add("            ),")
        $newLines.Add("          ),")
        $newLines.Add("          Center(")
        $newLines.Add("            child: Container(")
        $newLines.Add("              padding: const EdgeInsets.all(12),")
        $newLines.Add("              decoration: BoxDecoration(")
        $newLines.Add("                color: Colors.white.withOpacity(0.2),")
        $newLines.Add("                shape: BoxShape.circle,")
        $newLines.Add("                border: Border.all(color: Colors.white.withOpacity(0.4), width: 1.5),")
        $newLines.Add("              ),")
        $newLines.Add("              child: const Icon(")
        $newLines.Add("                PhosphorIconsFill.play,")
        $newLines.Add("                color: Colors.white,")
        $newLines.Add("                size: 40,")
        $newLines.Add("              ),")
        $newLines.Add("            ),")
        $newLines.Add("          ),")
        $newLines.Add("        ],")
        $newLines.Add("      ),")
        $newLines.Add("    );")
        $newLines.Add("  }")
        $inOldCourseImage = $true
        continue
    }

    if ($inOldCourseImage) {
        if ($line -eq "  }") {
            $inOldCourseImage = $false
        }
        continue
    }

    # Add NotchHandle and TabContent methods
    if ($line -like "*/// ✅ Tabs Content*") {
        $newLines.Add("  Widget _buildNotchHandle() {")
        $newLines.Add("    return Center(")
        $newLines.Add("      child: Container(")
        $newLines.Add("        margin: const EdgeInsets.symmetric(vertical: 12),")
        $newLines.Add("        width: 48,")
        $newLines.Add("        height: 5,")
        $newLines.Add("        decoration: BoxDecoration(")
        $newLines.Add("          color: Colors.grey.withOpacity(0.3),")
        $newLines.Add("          borderRadius: BorderRadius.circular(2.5),")
        $newLines.Add("        ),")
        $newLines.Add("      ),")
        $newLines.Add("    );")
        $newLines.Add("  }")
        $newLines.Add("")
        $newLines.Add("  Widget _buildStatsRow(bool isDark) {")
        $newLines.Add("    return Row(")
        $newLines.Add("      mainAxisAlignment: MainAxisAlignment.end,")
        $newLines.Add("      children: [")
        $newLines.Add('        _buildStatBadge("${lessons.length} درس", PhosphorIconsFill.videoCamera, isDark),')
        $newLines.Add("        const SizedBox(width: 12),")
        $newLines.Add('        _buildStatBadge("${pdfs.length} ملفات", PhosphorIconsFill.filePdf, isDark),')
        $newLines.Add("      ],")
        $newLines.Add("    );")
        $newLines.Add("  }")
        $newLines.Add("")
        $newLines.Add("  Widget _buildStatBadge(String label, IconData icon, bool isDark) {")
        $newLines.Add("    return Container(")
        $newLines.Add("      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),")
        $newLines.Add("      decoration: BoxDecoration(")
        $newLines.Add("        color: isDark ? Colors.white.withOpacity(0.05) : const Color(0xFFF8FAFC),")
        $newLines.Add("        borderRadius: BorderRadius.circular(12),")
        $newLines.Add("        border: Border.all(color: isDark ? Colors.white10 : Colors.black.withOpacity(0.05)),")
        $newLines.Add("      ),")
        $newLines.Add("      child: Row(")
        $newLines.Add("        mainAxisSize: MainAxisSize.min,")
        $newLines.Add("        children: [")
        $newLines.Add("          Text(")
        $newLines.Add("            label,")
        $newLines.Add("            style: GoogleFonts.cairo(")
        $newLines.Add("              fontSize: 13,")
        $newLines.Add("              fontWeight: FontWeight.w700,")
        $newLines.Add("              color: isDark ? Colors.white70 : const Color(0xFF475569),")
        $newLines.Add("            ),")
        $newLines.Add("          ),")
        $newLines.Add("          const SizedBox(width: 6),")
        $newLines.Add("          Icon(icon, size: 18, color: AppColors.sky),")
        $newLines.Add("        ],")
        $newLines.Add("      ),")
        $newLines.Add("    );")
        $newLines.Add("  }")
        $newLines.Add("")
        $newLines.Add("  Widget _buildBottomBar(bool isDark) {")
        $newLines.Add("    return Container(")
        $newLines.Add("      padding: const EdgeInsets.fromLTRB(24, 16, 24, 32),")
        $newLines.Add("      decoration: BoxDecoration(")
        $newLines.Add("        color: isDark ? const Color(0xFF0F172A).withOpacity(0.9) : Colors.white.withOpacity(0.9),")
        $newLines.Add("        boxShadow: [")
        $newLines.Add("          BoxShadow(")
        $newLines.Add("            color: Colors.black.withOpacity(0.05),")
        $newLines.Add("            blurRadius: 20,")
        $newLines.Add("            offset: const Offset(0, -4),")
        $newLines.Add("          ),")
        $newLines.Add("        ],")
        $newLines.Add("      ),")
        $newLines.Add("      child: Row(")
        $newLines.Add("        mainAxisAlignment: MainAxisAlignment.spaceBetween,")
        $newLines.Add("        children: [")
        $newLines.Add("          Container(")
        $newLines.Add("            decoration: BoxDecoration(")
        $newLines.Add("              gradient: AppColors.buttonGradient,")
        $newLines.Add("              borderRadius: BorderRadius.circular(16),")
        $newLines.Add("              boxShadow: [")
        $newLines.Add("                BoxShadow(")
        $newLines.Add("                  color: AppColors.sky.withOpacity(0.3),")
        $newLines.Add("                  blurRadius: 12,")
        $newLines.Add("                  offset: const Offset(0, 4),")
        $newLines.Add("                ),")
        $newLines.Add("              ],")
        $newLines.Add("            ),")
        $newLines.Add("            child: ElevatedButton(")
        $newLines.Add("              style: ElevatedButton.styleFrom(")
        $newLines.Add("                backgroundColor: Colors.transparent,")
        $newLines.Add("                shadowColor: Colors.transparent,")
        $newLines.Add("                padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 14),")
        $newLines.Add("                shape: RoundedRectangleBorder(")
        $newLines.Add("                  borderRadius: BorderRadius.circular(16),")
        $newLines.Add("                ),")
        $newLines.Add("              ),")
        $newLines.Add("              onPressed: _showPurchaseDialog,")
        $newLines.Add("              child: Text(")
        $newLines.Add('                "اشترك الآن",')
        $newLines.Add("                style: GoogleFonts.cairo(")
        $newLines.Add("                  color: Colors.white,")
        $newLines.Add("                  fontSize: 16,")
        $newLines.Add("                  fontWeight: FontWeight.w800,")
        $newLines.Add("                ),")
        $newLines.Add("              ),")
        $newLines.Add("            ),")
        $newLines.Add("          ),")
        $newLines.Add("          Column(")
        $newLines.Add("            crossAxisAlignment: CrossAxisAlignment.end,")
        $newLines.Add("            mainAxisSize: MainAxisSize.min,")
        $newLines.Add("            children: [")
        $newLines.Add("              Text(")
        $newLines.Add('                "${widget.price ?? 0} ج.م",')
        $newLines.Add("                style: GoogleFonts.cairo(")
        $newLines.Add("                  fontSize: 20,")
        $newLines.Add("                  fontWeight: FontWeight.w900,")
        $newLines.Add("                  color: isDark ? Colors.white : const Color(0xFF1E293B),")
        $newLines.Add("                ),")
        $newLines.Add("              ),")
        $newLines.Add("              Text(")
        $newLines.Add('                "السعر الإجمالي",')
        $newLines.Add("                style: GoogleFonts.cairo(")
        $newLines.Add("                  fontSize: 12,")
        $newLines.Add("                  fontWeight: FontWeight.w700,")
        $newLines.Add("                  color: Colors.grey,")
        $newLines.Add("                ),")
        $newLines.Add("              ),")
        $newLines.Add("            ],")
        $newLines.Add("          ),")
        $newLines.Add("        ],")
        $newLines.Add("      ),")
        $newLines.Add("    );")
        $newLines.Add("  }")
        $newLines.Add("")
        $newLines.Add("  /// ✅ Tabs Content")
        continue
    }

    $newLines.Add($line)
}

[System.IO.File]::WriteAllLines($path, $newLines, [System.Text.Encoding]::UTF8)
